extends Control
# Draft - Character selection UI for starting a run
# Uses DraftManager for business logic, this scene handles UI only
# Uses two TeamDisplay panels for consistent UI:
# - Options panel: shows draftable characters
# - Team panel: shows already drafted characters

@onready var background: ColorRect = $Background
@onready var instruction_label = $MainContainer/VBoxContainer/TopSection/InstructionLabel
@onready var options_section = $MainContainer/VBoxContainer/ContentScroll/ContentContainer/OptionsSection
@onready var options_display_container = $MainContainer/VBoxContainer/ContentScroll/ContentContainer/OptionsSection/OptionsDisplayContainer
@onready var team_display_container = $TeamDisplayContainer
@onready var confirm_button = $MainContainer/VBoxContainer/BottomButtons/ConfirmButton
@onready var back_button = $BackButton

# Preload scenes
const TeamDisplayScene = preload("res://scenes/components/team_display.tscn")

# Draft manager handles business logic
var draft_manager: DraftManager = null

# UI state
var options_team_display: Node = null
var your_team_display: Node = null
var select_buttons: Array = []  # SELECT buttons for each option


func _ready() -> void:
	_setup_draft_manager()
	_apply_visual_styling()

	confirm_button.pressed.connect(_on_confirm_pressed)
	back_button.pressed.connect(_on_back_pressed)

	# Hide team display until characters are drafted
	team_display_container.visible = false

	_setup_options_display()
	draft_manager.generate_options()
	_update_instruction()


func _setup_draft_manager() -> void:
	"""Create and connect to the draft manager."""
	draft_manager = DraftManager.new()
	draft_manager.options_generated.connect(_on_options_generated)
	draft_manager.character_drafted.connect(_on_character_drafted)
	draft_manager.draft_complete.connect(_on_draft_complete)


func _apply_visual_styling() -> void:
	"""Apply fantasy aesthetic styling."""
	background.color = GameConstants.COLOR_BG_DARK

	UIStyles.apply_button_styles(confirm_button)
	UIStyles.apply_button_styles(back_button)

	instruction_label.add_theme_color_override("font_color", GameConstants.COLOR_TEXT_LIGHT)


func _setup_options_display() -> void:
	"""Create the options TeamDisplay."""
	options_team_display = TeamDisplayScene.instantiate()
	options_display_container.add_child(options_team_display)
	# We'll set it up when options are generated


# =============================================================================
# DRAFT MANAGER SIGNAL HANDLERS
# =============================================================================

func _on_options_generated(options: Array, instances: Array) -> void:
	"""Handle new options being generated by the draft manager."""
	_update_options_display(instances)


func _on_character_drafted(_char_data: Dictionary, _char_instance: CharacterInstance) -> void:
	"""Handle a character being drafted."""
	# Return options display to overview mode
	if options_team_display:
		options_team_display.refresh()

	_update_team_display()
	_update_instruction()

	if not draft_manager.is_draft_complete():
		draft_manager.generate_options()


func _on_draft_complete(_team: Array) -> void:
	"""Handle draft completion."""
	_show_confirm_state()


# =============================================================================
# UI UPDATES
# =============================================================================

func _update_options_display(instances: Array) -> void:
	"""Update the options TeamDisplay with current options."""
	if options_team_display and instances.size() > 0:
		# Connect to overview_shown signal to add buttons whenever tiles are created
		if not options_team_display.overview_shown.is_connected(_on_options_overview_shown):
			options_team_display.overview_shown.connect(_on_options_overview_shown)

		options_team_display.setup(instances, "AVAILABLE CHARACTERS")
		# Buttons will be added via the overview_shown signal


func _on_options_overview_shown() -> void:
	"""Add SELECT buttons when overview is shown (initial or returning from details)."""
	# Wait a frame for tiles to be fully ready
	await get_tree().process_frame
	_create_select_buttons()


func _create_select_buttons() -> void:
	"""Create SELECT buttons inside each character tile."""
	select_buttons.clear()

	if not options_team_display:
		return

	# Use TeamDisplay's character_tiles array directly
	var tiles = options_team_display.character_tiles

	if tiles.is_empty():
		return

	var current_options = draft_manager.current_options

	for i in range(min(tiles.size(), current_options.size())):
		var tile = tiles[i]
		var option = current_options[i]

		if not is_instance_valid(tile):
			continue

		# Get the VBoxContainer inside the tile
		var vbox = tile.get_node_or_null("MarginContainer/VBoxContainer")
		if not vbox:
			continue

		# Skip if button already exists (vbox normally has 2 children: Portrait and NameLabel)
		if vbox.get_child_count() > 2:
			continue

		# Add a spacer to push button to bottom
		var spacer = Control.new()
		spacer.size_flags_vertical = Control.SIZE_EXPAND_FILL
		vbox.add_child(spacer)

		# Create the button
		var button = Button.new()
		button.custom_minimum_size = Vector2(0, 36)
		button.size_flags_horizontal = Control.SIZE_EXPAND_FILL

		# Set button text based on ownership
		if option["is_owned"]:
			button.text = "SELECT"
		else:
			button.text = "UNLOCK (%d)" % option["unlock_cost"]

		UIStyles.apply_button_styles(button)
		button.pressed.connect(_on_option_button_pressed.bind(i))

		vbox.add_child(button)
		select_buttons.append(button)


func _on_option_button_pressed(option_index: int) -> void:
	"""Handle SELECT/UNLOCK button press for an option."""
	var option = draft_manager.get_option_at(option_index)
	if option.is_empty():
		return

	# Check if owned or needs unlock
	if option["is_owned"]:
		draft_manager.select_character(option["char_data"])
	else:
		draft_manager.unlock_and_select(option["char_data"], option["unlock_cost"])


func _update_team_display() -> void:
	"""Update the team display with drafted characters."""
	var drafted_instances = draft_manager.drafted_instances

	if drafted_instances.is_empty():
		team_display_container.visible = false
		return

	team_display_container.visible = true

	# Create team display if needed
	if your_team_display == null:
		your_team_display = TeamDisplayScene.instantiate()
		team_display_container.add_child(your_team_display)

	your_team_display.setup(drafted_instances, "YOUR TEAM")


func _update_instruction() -> void:
	"""Update instruction text."""
	if not draft_manager.is_draft_complete():
		instruction_label.text = "SELECT CHARACTER %d OF %d" % [
			draft_manager.get_current_selection_number(),
			GameConstants.TEAM_SIZE
		]
	else:
		instruction_label.text = "TEAM COMPLETE - READY TO START"
	print("Draft: Instruction updated to: %s" % instruction_label.text)


func _show_confirm_state() -> void:
	"""Show confirm state when team is complete."""
	print("Draft: Showing confirm state (team complete)")

	# Hide options section (display + buttons)
	options_section.visible = false

	# Show confirm button
	confirm_button.visible = true


# =============================================================================
# BUTTON HANDLERS
# =============================================================================

func _on_reroll_pressed() -> void:
	"""Handle reroll button press (backend kept for future use)."""
	if PlayerAccount.spend_reroll_token():
		print("Draft: Rerolling options...")
		draft_manager.generate_options()
	else:
		print("Draft: No reroll tokens available")


func _on_confirm_pressed() -> void:
	"""Start the run with drafted characters."""
	if not draft_manager.is_draft_complete():
		push_error("Draft: Must select exactly %d characters" % GameConstants.TEAM_SIZE)
		return

	print("Draft: Starting run with drafted team...")

	# Extract character IDs
	var char_ids = draft_manager.get_drafted_character_ids()

	print("Draft: Character IDs: %s" % str(char_ids))

	# Start run
	RunManager.start_new_run(char_ids)

	print("Draft: Run started, navigating to run_view...")

	# Navigate to run view using SceneManager
	SceneManager.go_to_run_view()


func _on_back_pressed() -> void:
	"""Return to main menu."""
	SceneManager.go_to_main_menu()
