class_name ErrorCodes
## Centralized error code constants for all manager operations.

# Gold / Economy
const INSUFFICIENT_GOLD := "INSUFFICIENT_GOLD"
const INVALID_GOLD_AMOUNT := "INVALID_GOLD_AMOUNT"

# Reputation
const INVALID_REPUTATION_AMOUNT := "INVALID_REPUTATION_AMOUNT"
const ALREADY_DEFEATED := "ALREADY_DEFEATED"

# Characters
const INVALID_CHARACTER_ID := "INVALID_CHARACTER_ID"
const GRID_FULL := "GRID_FULL"
const GRID_POSITION_OCCUPIED := "GRID_POSITION_OCCUPIED"
const GRID_POSITION_INVALID := "GRID_POSITION_INVALID"
const CHARACTER_NOT_FOUND := "CHARACTER_NOT_FOUND"

# Inventory
const INVENTORY_FULL := "INVENTORY_FULL"
const ITEM_NOT_FOUND := "ITEM_NOT_FOUND"
const INVALID_ITEM := "INVALID_ITEM"
const INVALID_SLOT := "INVALID_SLOT"

# Skills
const SKILL_NOT_FOUND := "SKILL_NOT_FOUND"
const INVALID_SKILL := "INVALID_SKILL"
const DUPLICATE_SKILL := "DUPLICATE_SKILL"

# Progression
const MAX_LEVEL_REACHED := "MAX_LEVEL_REACHED"
const INVALID_XP_AMOUNT := "INVALID_XP_AMOUNT"
const INVALID_ROUND := "INVALID_ROUND"

# Run State
const NO_ACTIVE_RUN := "NO_ACTIVE_RUN"
const RUN_ALREADY_ACTIVE := "RUN_ALREADY_ACTIVE"
const SAVE_FAILED := "SAVE_FAILED"
const LOAD_FAILED := "LOAD_FAILED"
